[project]
name = 'Digital-Rights-Management-for-Content-Creators'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.content-registration]
path = 'contracts/content-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
